version: '3.8'

services:
  client:
    build:
      context: ../src/client
    image: client
    ports:
      - "4200:80"
    depends_on:
      - backend
      - validation

  backend:
    build:
      context: ../src/backend
    image: backend
    environment:
      - ConnectionStrings__Default=server=mssql;user id=sa;password=Pass@word;

      - Services__SentenceSplitter=http://sentence-splitter:5000
      - Services__TokenEnricher=http://token-enricher:5001
      - Services__NamedEntityExtractor=http://named-entity-extractor:5002
    ports:
      - "5000:80"
    depends_on:
      - mssql
      - sentence-splitter
      - token-enricher
      - named-entity-extractor

  validation:
    build:
      context: ../src/validation
    image: validation
    ports:
      - "5001:80"
  
  sentence-splitter:
    build:
      context: ../src/nlp/sentence_splitter
    image: sentence-splitter
    ports:
      - "5002:5000"

  token-enricher:
    build:
      context: ../src/nlp/token_enricher
    image: token-enricher
    ports:
      - "5003:5001"

  named-entity-extractor:
    build:
      context: ../src/nlp/named_entity_extractor
    image: named-entity-extractor
    ports:
      - "5004:5002"

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"