version: '3.8'

services:
  backend:
    build:
      context: ../src/backend
    image: backend
    ports:
      - "5000:80"
    depends_on:
      - mssql

  validation:
    build:
      context: ../src/validation
    image: validation
    ports:
      - "5001:80"

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  sentence-splitter:
    build:
      context: ../src/nlp/sentence_splitter
    image: sentence-splitter
    ports:
      - "5002:5000"

  token-enricher:
    build:
      context: ../src/nlp/token_enricher
    image: token-enricher
    ports:
      - "5003:5001"

  named-entity-extractor:
    build:
      context: ../src/nlp/named_entity_extractor
    image: named-entity-extractor
    ports:
      - "5004:5002"